<?php

// +---------------------------------------------------------------------------+
// | Menu Plugin                                                               |
// +---------------------------------------------------------------------------+
// | image_upload.php                                                          |
// |                                                                           |
// | Security helpers for optional legacy menu presentation images.            |
// +---------------------------------------------------------------------------+

if (!defined('VERSION')) {
    die('This file can not be used on its own.');
}

/**
 * Validate and store one optional legacy menu presentation image.
 *
 * The upload feature is retained only for backwards compatibility with the
 * legacy Menu renderer. Modern themes should own their presentation assets.
 *
 * @param array  $file        One entry from $_FILES
 * @param string $prefix      Server-side filename prefix
 * @param string $oldFilename Previously configured filename, if any
 * @return string Empty string when no valid upload was stored, otherwise the
 *                generated basename.
 */
function MENU_storeLegacyImageUpload($file, $prefix, $oldFilename = '')
{
    if (!is_array($file)) {
        return '';
    }

    $error = isset($file['error']) ? (int) $file['error'] : UPLOAD_ERR_NO_FILE;
    if ($error === UPLOAD_ERR_NO_FILE) {
        return '';
    }
    if ($error !== UPLOAD_ERR_OK) {
        return '';
    }

    $tmpName = isset($file['tmp_name']) ? (string) $file['tmp_name'] : '';
    $size = isset($file['size']) ? (int) $file['size'] : 0;
    if ($tmpName === '' || $size < 1 || $size > 2097152 || !is_uploaded_file($tmpName)) {
        return '';
    }

    $imageInfo = @getimagesize($tmpName);
    if ($imageInfo === false || !isset($imageInfo[0], $imageInfo[1], $imageInfo[2])) {
        return '';
    }

    $width = (int) $imageInfo[0];
    $height = (int) $imageInfo[1];
    if ($width < 1 || $height < 1 || $width > 4096 || $height > 4096
        || ($width * $height) > 16777216) {
        return '';
    }

    switch ((int) $imageInfo[2]) {
        case IMAGETYPE_PNG:
            $extension = '.png';
            break;
        case IMAGETYPE_GIF:
            $extension = '.gif';
            break;
        case IMAGETYPE_JPEG:
            $extension = '.jpg';
            break;
        default:
            return '';
    }

    $allowedPrefixes = array('menu_bg', 'menu_hover_bg', 'menu_parent');
    if (!in_array($prefix, $allowedPrefixes, true)) {
        return '';
    }

    if (!MENU_ensureImageDir()) {
        return '';
    }

    $directory = MENU_imageDir();
    if ($directory === '' || !is_dir($directory) || !is_writable($directory)) {
        return '';
    }

    $token = substr(sha1(uniqid((string) mt_rand(), true)), 0, 16);
    $newFilename = $prefix . '_' . $token . $extension;
    $destination = $directory . $newFilename;

    if (!move_uploaded_file($tmpName, $destination)) {
        return '';
    }
    @chmod($destination, 0644);

    // Delete only filenames previously generated by this plugin. Never unlink
    // arbitrary configuration values or bundled/static assets.
    $oldFilename = basename((string) $oldFilename);
    if ($oldFilename !== ''
        && preg_match('/^menu_(?:bg|hover_bg|parent)_?[a-f0-9]{8,40}\.(?:png|gif|jpe?g)$/i', $oldFilename)) {
        $oldPath = $directory . $oldFilename;
        if ($oldPath !== $destination && is_file($oldPath) && !is_link($oldPath)) {
            @unlink($oldPath);
        }
    }

    return $newFilename;
}

/**
 * Render a preview only when a configured legacy image really exists.
 *
 * @param string $filename Configured basename
 * @param bool   $fixedSize Whether to constrain the preview to 27x27
 * @return string
 */
function MENU_legacyImagePreview($filename, $fixedSize = true)
{
    $filename = basename(trim((string) $filename));
    if ($filename === '' || !preg_match('/\.(?:png|gif|jpe?g)$/i', $filename)) {
        return '';
    }

    $directory = MENU_imageDir();
    $url = MENU_imageUrl();
    if ($directory === '' || $url === '') {
        return '';
    }

    $path = $directory . $filename;
    if (!is_file($path) || is_link($path)) {
        return '';
    }

    $src = htmlspecialchars($url . rawurlencode($filename), ENT_QUOTES, 'UTF-8');
    $size = $fixedSize ? ' width="27" height="27"' : '';

    return '<img src="' . $src . '"' . $size
        . ' style="vertical-align:middle;border:none;" alt=""' . XHTML . '>';
}
